### ISSUE TITLE
Using custom listen_port does not work

### ISSUE THREAD

**Issue by lieryan** [atomic-penguin/cookbook-gitlab#90]
In [templates/default/gitlab.yml.erb](https://github.com/atomic-penguin/cookbook-gitlab/blob/0e9a8c92d75cc715ed61bb3bcacbe3323884e76c/templates/default/gitlab.yml.erb#L19)

```
  ## GitLab settings
  gitlab:
    ## Web server settings
    host: <%= @fqdn %>
    port: <%= @port %>
    https: <%= @https_boolean %>
```

The `<%= @port %>` is always empty because there is no such variable defined. Instead it should have been `<%= node['gitlab']['listen_port'] %>`.

Things that breaks due to this includes:

1. The HTTPS git repository URL generated in the project overview page does not include the port number
2. Pushing through the git HTTPS URL fails even after adding the port number
